INSERT INTO PERFIL (ID, DESCRICAO, ATIVO) VALUES (1, 'Administrador', true);
INSERT INTO PERFIL (ID, DESCRICAO, ATIVO) VALUES (2, 'Gerente', true);
INSERT INTO PERFIL (ID, DESCRICAO, ATIVO) VALUES (3, 'Funcionário', true);
INSERT INTO PERFIL (ID, DESCRICAO, ATIVO) VALUES (4, 'Técnico', true);